ALTER TABLE kb_doc
  ADD COLUMN IF NOT EXISTS body_html MEDIUMTEXT NULL AFTER body_md,
  ADD COLUMN IF NOT EXISTS static_version INT NOT NULL DEFAULT 0 AFTER version,
  ADD COLUMN IF NOT EXISTS static_html_url VARCHAR(1024) NULL AFTER static_version;
